# Generated by Django 4.2.6 on 2024-08-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NftStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, unique='/uploads/nft_store', upload_to='')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.URLField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('link_text', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.URLField(blank=True, max_length=150, null=True)),
                ('link2_text', models.CharField(blank=True, max_length=150, null=True)),
                ('link2', models.URLField(blank=True, max_length=150, null=True)),
                ('link3_text', models.CharField(blank=True, max_length=150, null=True)),
                ('link3', models.URLField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('token', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('bonus_claimed', models.BooleanField(default=False)),
                ('last_bonus_claim', models.DateTimeField(blank=True, null=True)),
                ('current_bonus_day', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='userprofit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.IntegerField(default=0)),
                ('getdate', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home_Module.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField(default=99999)),
                ('energy', models.BigIntegerField(default=1000)),
                ('level', models.IntegerField(default=1)),
                ('ads', models.IntegerField(default=0)),
                ('luckywheel', models.IntegerField(default=0)),
                ('get_profit', models.BooleanField(default=True)),
                ('blueTicks', models.BooleanField(default=False)),
                ('tap', models.IntegerField(default=2)),
                ('bostlimit', models.IntegerField(default=10)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('invite', models.ManyToManyField(blank=True, related_name='invites', to='Home_Module.telegramuser')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to='Home_Module.telegramuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Module.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gift', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True, null=True)),
                ('user', models.ManyToManyField(blank=True, to='Home_Module.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='giftcodeandroidapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftcode', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('coin', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Module.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='EarningsYoutubeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.URLField(blank=True, max_length=150, null=True)),
                ('giftCount', models.IntegerField(default=0)),
                ('user', models.ManyToManyField(blank=True, to='Home_Module.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('giftCount', models.IntegerField(default=0)),
                ('day', models.IntegerField()),
                ('user', models.ManyToManyField(blank=True, related_name='dailyBonus', to='Home_Module.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Module.telegramuser')),
            ],
            options={
                'unique_together': {('user', 'activity_time')},
            },
        ),
    ]
