# Generated by Django 4.2.6 on 2024-08-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
