# Generated by Django 4.2.6 on 2024-08-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0003_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
