# Generated by Django 4.2.6 on 2024-08-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0005_dailyactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyActivity',
        ),
    ]
