# Generated by Django 4.2.6 on 2024-08-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0006_delete_dailyactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='last_bonus_claim',
            new_name='silence_until',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_silenced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_request_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
