# Generated by Django 4.2.6 on 2024-08-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0007_rename_last_bonus_claim_telegramuser_silence_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_silenced',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_request_time',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='request_count',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='silence_until',
        ),
    ]
