# Generated by Django 4.2.6 on 2024-08-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0008_remove_telegramuser_is_silenced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='reward_given',
            field=models.BooleanField(default=False),
        ),
    ]
