# Generated by Django 4.2.6 on 2024-08-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0010_alter_userdata_get_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
    ]
