# Generated by Django 4.2.6 on 2024-08-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0011_alter_userdata_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='count',
            field=models.BigIntegerField(default=99999),
        ),
    ]
