# Generated by Django 4.2.6 on 2024-08-23 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0013_fullenergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullenergy',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='booststapcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Module.telegramuser')),
            ],
        ),
    ]
