# Generated by Django 4.2.6 on 2024-08-23 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0014_alter_fullenergy_count_booststapcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booststapcount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Module.userdata'),
        ),
        migrations.AlterField(
            model_name='fullenergy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Module.userdata'),
        ),
    ]
