# Generated by Django 4.2.6 on 2024-08-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0015_alter_booststapcount_user_alter_fullenergy_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Module.userdata')),
            ],
        ),
    ]
