# Generated by Django 4.2.6 on 2024-08-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0016_multitap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booststapcount',
            name='count',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='fullenergy',
            name='count',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='multitap',
            name='count',
            field=models.IntegerField(default=3),
        ),
    ]
