# Generated by Django 4.2.6 on 2024-08-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0018_booststapcount_datetime_fullenergy_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booststapcount',
            name='DateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fullenergy',
            name='DateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='multitap',
            name='DateTime',
            field=models.DateTimeField(),
        ),
    ]
