# Generated by Django 4.2.6 on 2024-08-24 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0022_globalrechargetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullenergy',
            name='last_recharged',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
