# Generated by Django 4.2.6 on 2024-08-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0023_fullenergy_last_recharged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booststapcount',
            name='DateTime',
        ),
        migrations.RemoveField(
            model_name='fullenergy',
            name='DateTime',
        ),
        migrations.RemoveField(
            model_name='fullenergy',
            name='last_recharged',
        ),
        migrations.RemoveField(
            model_name='multitap',
            name='DateTime',
        ),
    ]
