# Generated by Django 4.2.6 on 2024-08-25 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0024_remove_booststapcount_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booststapcount',
            name='DateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fullenergy',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multitap',
            name='DateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
