# Generated by Django 4.2.6 on 2024-08-24 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0025_booststapcount_datetime_fullenergy_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullenergy',
            name='last_reset_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
