# Generated by Django 4.2.6 on 2024-08-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0026_fullenergy_last_reset_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullenergy',
            name='last_reset_time',
        ),
    ]
