# Generated by Django 4.2.6 on 2024-08-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0028_tasks_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='completed',
        ),
    ]
