# Generated by Django 4.2.6 on 2024-08-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0030_refferaltaks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refferaltaks',
            name='user',
        ),
        migrations.AddField(
            model_name='refferaltaks',
            name='user',
            field=models.ManyToManyField(blank=True, to='Home_Module.userdata'),
        ),
    ]
