# Generated by Django 4.2.6 on 2024-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0031_remove_refferaltaks_user_refferaltaks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='refferaltaks',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
