# Generated by Django 4.2.6 on 2024-08-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0032_refferaltaks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='energy',
            field=models.BigIntegerField(default=3000),
        ),
        migrations.CreateModel(
            name='EstimatedDollarIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Module.userdata')),
            ],
        ),
    ]
