# Generated by Django 4.2.6 on 2024-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0034_lottery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='user',
        ),
        migrations.AddField(
            model_name='lottery',
            name='user',
            field=models.ManyToManyField(blank=True, to='Home_Module.userdata'),
        ),
    ]
