# Generated by Django 4.2.6 on 2024-08-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0036_alter_lottery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='user',
        ),
        migrations.CreateModel(
            name='lotteryamount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Module.userdata')),
            ],
        ),
    ]
