# Generated by Django 4.2.6 on 2024-08-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0038_botlinks_alter_userdata_count_alter_userdata_tap_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotLinks',
        ),
    ]
