# Generated by Django 4.2.6 on 2024-08-30 13:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0041_alter_giftcodeandroidapp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateddollarincome',
            name='count',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='get_profit',
            field=models.BooleanField(default=True),
        ),
    ]
