# Generated by Django 4.2.6 on 2024-08-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0042_alter_estimateddollarincome_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateddollarincome',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
