# Generated by Django 4.2.6 on 2024-08-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0043_alter_estimateddollarincome_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='user_amount',
            field=models.IntegerField(default=10),
        ),
    ]
