# Generated by Django 4.2.6 on 2024-09-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0044_lottery_user_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryamount',
            name='lottery',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Home_Module.lottery'),
            preserve_default=False,
        ),
    ]
