# Generated by Django 4.2.6 on 2024-09-01 11:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0046_alter_lotteryamount_lottery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('count_added', models.BigIntegerField(default=0)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='Home_Module.userdata')),
            ],
        ),
    ]
